//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class doctor_timing
    {
        public int id { get; set; }
        public string Day { get; set; }
        public string Timing { get; set; }
    
        public virtual Register Register { get; set; }
    }
}
