//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hospital_managementEntities : DbContext
    {
        public hospital_managementEntities()
            : base("name=hospital_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History_doctor> History_doctor { get; set; }
        public virtual DbSet<Patient_Prescription> Patient_Prescription { get; set; }
        public virtual DbSet<Register> Registers { get; set; }
        public virtual DbSet<doctor_timing> doctor_timing { get; set; }
        public virtual DbSet<Patient_History> Patient_History { get; set; }
    }
}
