//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication15
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient_Prescription
    {
        public int SR { get; set; }
        public int Registerid { get; set; }
        public string Medicine { get; set; }
        public int Duration { get; set; }
        public Nullable<int> Morning { get; set; }
        public Nullable<int> Noon { get; set; }
        public Nullable<int> Evening { get; set; }
    }
}
